### PR TITLE
Deb packaging

### PR DESCRIPTION
**Pull request by lukeyeager**
Based on #2 from @borisfom. I've squashed his commits into a single commit and present my changes as a separate commit for clarity.

## To install
Get packages from here: https://github.com/lukeyeager/nccl/tree/packages
```sh
$ sudo dpkg -i libnccl1_1.0.2-2_amd64.deb libnccl-dev_1.0.2-2_amd64.deb
$ dpkg -l | grep nccl
ii  libnccl-dev  1.0.2-2  amd64        NVIDIA Communication Collectives Library (NCCL) Development Files
ii  libnccl1     1.0.2-2  amd64        NVIDIA Communication Collectives Library (NCCL) Runtime
```

## Questions

1) I'm seeing some troubling warnings in the logs that make me think we aren't linking to CUDA correctly:
```
dpkg-shlibdeps: warning: symbol cudaMemcpy used by debian/libnccl1/usr/lib/libnccl.so.1.0.2 found in none of the libraries
dpkg-shlibdeps: warning: symbol cudaStreamWaitEvent used by debian/libnccl1/usr/lib/libnccl.so.1.0.2 found in none of the libraries
dpkg-shlibdeps: warning: symbol __cudaUnregisterFatBinary used by debian/libnccl1/usr/lib/libnccl.so.1.0.2 found in none of the libraries
dpkg-shlibdeps: warning: symbol cudaGetErrorString used by debian/libnccl1/usr/lib/libnccl.so.1.0.2 found in none of the libraries
dpkg-shlibdeps: warning: symbol cudaMalloc used by debian/libnccl1/usr/lib/libnccl.so.1.0.2 found in none of the libraries
dpkg-shlibdeps: warning: symbol cudaGetDevice used by debian/libnccl1/usr/lib/libnccl.so.1.0.2 found in none of the libraries
dpkg-shlibdeps: warning: symbol dlclose used by debian/libnccl1/usr/lib/libnccl.so.1.0.2 found in none of the libraries
dpkg-shlibdeps: warning: symbol cudaConfigureCall used by debian/libnccl1/usr/lib/libnccl.so.1.0.2 found in none of the libraries
dpkg-shlibdeps: warning: symbol cudaFree used by debian/libnccl1/usr/lib/libnccl.so.1.0.2 found in none of the libraries
dpkg-shlibdeps: warning: symbol cudaLaunch used by debian/libnccl1/usr/lib/libnccl.so.1.0.2 found in none of the libraries
dpkg-shlibdeps: warning: 24 other similar warnings have been skipped (use -v to see them all)
```
2) Boris, the tests aren't running for me when I build the deb package - why did you have turn off the tests explicitly in `debian/rules`?

3) How do I actually run the tests? `make test` only builds the tests - it doesn't run them.

## Differences

Here are the main differences between this PR and #2:

* Using `libnccl1` and `libnccl-dev` for the package names ([see](https://www.debian.org/doc/debian-policy/ch-sharedlibs.html#s-sharedlibs-runtime) [here](https://www.debian.org/doc/debian-policy/ch-sharedlibs.html#s-sharedlibs-dev))
* Bump version to 1.0.2 to match what Boris already did for the deb packaging
  * Started using debian revisions ([see here](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version))
* Don't require that the user install a specific driver version with a deb package
* Use a symlink to `LICENSE.txt` to avoid possible mis-matched licenses
* Don't create a `.postinst` script explicitly - let debhelper do it

### CODE REVIEW

**Comment by borisfom** [comment]
Luke: 
Yes I saw those warnings, too. I assume as the tests do link, we can ignore them.
(I built with cow builder, if you are interested  I have a cow with cuda-toolkit preinstalled.)

The test: originally I have disabled it because 'make test' wanted to link the test executables with nvidia-ml. As per communication with nccl team, nvidia-ml is also not used - but as you noted as well, making tests without running them makes not a lot of sense, so I planned to restore test phase after nccl team come up with a test script.

**Comment by lukeyeager** [comment]
> I assume as the tests do link, we can ignore them.

I'm not sure I'm comfortable with that. It doesn't look like nccl is linking to CUDA at all:
```sh
$ ldd /usr/lib/libnccl.so.1
	linux-vdso.so.1 =>  (0x00007ffea95d5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5e9432c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5e96c32000)
```
Should it link? It doesn't look like the build-from-source build links to CUDA either:
```sh
$ ldd build/lib/libnccl.so
	linux-vdso.so.1 =>  (0x00007ffffd9e8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe6b8240000)
```
The tests do, though:
```sh
$ ldd build/test/reduce_scatter_test
	linux-vdso.so.1 =>  (0x00007fff44f51000)
	libnccl.so.1 => /usr/lib/libnccl.so.1 (0x00007f41b6836000)
	libcudart.so.7.0 => /usr/local/cuda-7.0/targets/x86_64-linux/lib/libcudart.so.7.0 (0x00007f41b65d9000)
	libcurand.so.7.0 => /usr/local/cuda-7.0/targets/x86_64-linux/lib/libcurand.so.7.0 (0x00007f41b2d76000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f41b2a72000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f41b285c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f41b2497000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f41b2293000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f41b2075000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f41b1e6d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f41b1b67000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f41b8d77000)
```
/cc @nluehr

**Comment by lukeyeager** [comment]
Apparently cublas doesn't link to CUDA either. I guess the only time that could be an issue is if somebody wanted to link to NCCL with an application without any CUDA code in it. As long as there's some CUDA code in the application, then CUDA will be linked for NCCL as well.

If I have that right, then I think we can merge this. We can always go back and fix something in the Makefile later - this isn't really a packaging concern at all.

**Comment by borisfom** [comment]
Agreed. Let's start with this.

**Comment by borisfom** [comment]
Should we also merge 'packages' branch so the binaries are available in the master repo ?

**Pull request merged**
