### PR TITLE
Add pkgconfig file (v2)

### PR DESCRIPTION
**Pull request by sl1pkn07**
generate and install pkgconfig file (https://www.freedesktop.org/wiki/Software/pkg-config/)

related: #186

(ammend from the PR #188)

### CODE REVIEW

**Comment by sl1pkn07** [comment]
fua ><

sorry guys

**Comment by sjeaugey** [comment]
What's the reason for that second PR ? I don't see any difference with #188.

**Comment by sjeaugey** [comment]
Sorry -- didn't see you closed it.

**Comment by sl1pkn07** [comment]
yep. 

ammend the previous pr, but i forgot do git  add file before amend, :/

sorry:


BTW, is possible change the commits in a created PR? how?

**Comment by sjeaugey** [comment]
If you commit and push to your branch, I think the changes will be reflected in the PR. Then when we merge we can squash all commits into a single one (for a clean history).

**Comment by sl1pkn07** [comment]
seems not work like expected if the pr is from the first commit of the new branch. because the 188 and 189 did not update with the ammend commit

if you can, plesae remove the pr 188 and 189 for clear the history

very sorry and greetings

**Comment by sjeaugey** [comment]
sl1pkn07 force-pushed the sl1pkn07:pkgconfig branch from b2a6c1e to 08c84e4 an hour ago

**Comment by sl1pkn07** [comment]
yep, i force it, but in the 188 and 189 pr (web) still show the unammend commit

**Comment by sjeaugey** [comment]
> yep, i force it, but in the 188 and 189 pr (web) still show the unammend commit

PR #190 (which is still open) shows at the end :
« Add more commits by pushing to the pkgconfig branch on sl1pkn07/nccl. »
While 188/189 don't because (I believe) they are closed. 188 got the commit from 189 before being closed.

**Comment by sl1pkn07** [comment]
yep, you are rigth, seems in the pr 188 the review comments keep in the web the old code instead of the new code, and in the 189 not reflect this because you say

all "ok" then

if you can, please remove the pr 188 and 189 from the history, and keep/reviewed the pr 190. i be more carefull in the next time

greetings

**Comment by sjeaugey** [comment]
I don't think I can delete anything (not even hide it). But that doesn't really matter. And don't worry too much about it, we all struggle on our first Github PR :-)

**Pull request closed without merging**
