### PR TITLE
Add pkgconfig file

### PR DESCRIPTION
**Pull request by sl1pkn07**
generate and install pkgconfig file (https://www.freedesktop.org/wiki/Software/pkg-config/)

related: #186

### CODE REVIEW

**Comment by sl1pkn07** [comment]
i hate/need learn more about git :S

**Comment by sjeaugey** [comment]
#189 was merged so I guess we can close this one.

**Comment by sjeaugey** [comment]
My bad. It wasn't merged. Re-opening.

**Comment by sl1pkn07** [comment]
rebased (?)

**Comment by sjeaugey** [comment]
Thanks for the rebase. Merged it for real this time.

**Comment by sl1pkn07** [comment]
thanks to you

greetings

**Pull request merged**
