### PR TITLE
2.5.6-1

### PR DESCRIPTION
**Pull request by sjeaugey**
Add LL128 Protocol.

Rewrite the topology detection and tree/ring creation (#179). Improve
tree performance by sending/receiving from different GPUs. Add
model-based tuning to switch between the different algorithms and
protocols.

Rework P2P/SHM detection in containers (#155, #248).

Detect duplicated devices and return an error (#231).

Add tuning for GCP

### CODE REVIEW

**Comment by sjeaugey** [comment]
This is a preview branch of NCCL 2.5.

The summary says it all, it's a big rewrite, so any testing is appreciated !

@keisukefukuda @alsrgv @teng-li @pietern @lowintelligence @ashuatibm

**Comment by kuenishi** [comment]
Hi Sylvain, I tried a bit and I think I found an issue. With single-node multi-GPU case first communicator creation doesn't success to me. `ncclCommInitRank()` returns system error. Logs of failure at 2.5.1, success at 2.4.2 and reproduction script is https://gist.github.com/kuenishi/d8a1b45c1e157e7f86e9d0ca315b1daf .

 Although it's Python with our thin wrapper, whose `nccl.NcclCommunicator` code is here> https://github.com/cupy/cupy/blob/master/cupy/cuda/nccl.pyx#L250-L256

**Comment by sjeaugey** [comment]
Thanks for the feedback.

We'll try to push an update today, fixing a few things, including, hopefully, this error :
```
chainer-dev2:645:645 [1] misc/nvmlwrap.cc:174 NCCL WARN nvmlDeviceGetHandleByIndex() failed: Invalid Argument 
```
About this error :
```
chainer-dev2:644:644 [0] transport/net_ib.cc:120 NCCL WARN NET/IB : Unable to open device mlx5_0
```
did you see it with NCCL 2.4 or is it also something new in 2.5 ?

**Comment by kuenishi** [comment]
Thanks, I'm looking forward to the fix.

> About this error :
> 
> ```
> chainer-dev2:644:644 [0] transport/net_ib.cc:120 NCCL WARN NET/IB : Unable to open device mlx5_0
> ```
> 
> did you see it with NCCL 2.4 or is it also something new in 2.5 ?

I saw that line in both [log of 2.4](https://gist.github.com/kuenishi/d8a1b45c1e157e7f86e9d0ca315b1daf#file-success-log) and [log of 2.5](https://gist.github.com/kuenishi/d8a1b45c1e157e7f86e9d0ca315b1daf#file-console-log). The former worked fine so I didn't care - could be an environmental issue. My guess is that the pod has no infiniband devices (`/dev/infiniband/*`) assigned, though the hardware has actual InfiniBand devices attached. Maybe NCCL tried to load them but failed somehow?

**Comment by sjeaugey** [comment]
@kuenishi let us know if it is fixed now. Thanks !

**Comment by kuenishi** [comment]
@sjeaugey I've confirmed it was fixed with latest version:
```
kota@chainer-dev2:~$ NCCL_DEBUG=INFO mpirun -np 2 python3 nccl25.py 
chainer-dev2:195:195 [0] NCCL INFO Bootstrap : Using [0]eth0:172.23.228.238<0>
chainer-dev2:195:195 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).

chainer-dev2:195:195 [0] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed

chainer-dev2:195:195 [0] transport/net_ib.cc:120 NCCL WARN NET/IB : Unable to open device mlx5_1

chainer-dev2:195:195 [0] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed

chainer-dev2:195:195 [0] transport/net_ib.cc:120 NCCL WARN NET/IB : Unable to open device mlx5_0
chainer-dev2:195:195 [0] NCCL INFO NET/IB : No device found.
chainer-dev2:195:195 [0] NCCL INFO NET/Socket : Using [0]eth0:172.23.228.238<0>
NCCL version 2.5.3+cuda10.1
chainer-dev2:196:196 [1] NCCL INFO Bootstrap : Using [0]eth0:172.23.228.238<0>
chainer-dev2:196:196 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).

chainer-dev2:196:196 [1] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed

chainer-dev2:196:196 [1] transport/net_ib.cc:120 NCCL WARN NET/IB : Unable to open device mlx5_1

chainer-dev2:196:196 [1] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed

chainer-dev2:196:196 [1] transport/net_ib.cc:120 NCCL WARN NET/IB : Unable to open device mlx5_0
chainer-dev2:196:196 [1] NCCL INFO NET/IB : No device found.
chainer-dev2:196:196 [1] NCCL INFO NET/Socket : Using [0]eth0:172.23.228.238<0>
chainer-dev2:195:195 [0] NCCL INFO Setting affinity for GPU 0 to 3ffff0,0003ffff
chainer-dev2:196:196 [1] NCCL INFO Setting affinity for GPU 1 to 3ffff0,0003ffff
chainer-dev2:196:196 [1] NCCL INFO Could not find real path of /sys/class/net/eth0/device
chainer-dev2:196:196 [1] NCCL INFO include/net.h:19 -> 2
chainer-dev2:195:195 [0] NCCL INFO Could not find real path of /sys/class/net/eth0/device
chainer-dev2:195:195 [0] NCCL INFO include/net.h:19 -> 2
chainer-dev2:196:196 [1] NCCL INFO Threads per block : 512/640/256
chainer-dev2:196:196 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64
chainer-dev2:196:196 [1] NCCL INFO Trees [0] -1/-1/-1->1->0|0->1->-1/-1/-1 [1] -1/-1/-1->1->0|0->1->-1/-1/-1
chainer-dev2:195:195 [0] NCCL INFO Channel 00/02 :    0   1
chainer-dev2:195:195 [0] NCCL INFO Channel 01/02 :    0   1
chainer-dev2:195:195 [0] NCCL INFO Threads per block : 512/640/256
chainer-dev2:195:195 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64
chainer-dev2:195:195 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1|-1->0->1/-1/-1 [1] 1/-1/-1->0->-1|-1->0->1/-1/-1
chainer-dev2:195:195 [0] NCCL INFO Ring 00 : 0[1d000] -> 1[3f000] via direct shared memory
chainer-dev2:196:196 [1] NCCL INFO Ring 00 : 1[3f000] -> 0[1d000] via direct shared memory
chainer-dev2:195:195 [0] NCCL INFO Ring 01 : 0[1d000] -> 1[3f000] via direct shared memory
chainer-dev2:196:196 [1] NCCL INFO Ring 01 : 1[3f000] -> 0[1d000] via direct shared memory
chainer-dev2:195:195 [0] NCCL INFO comm 0x4650520 rank 0 nranks 2 cudaDev 0 busId 1d000 - Init COMPLETE
chainer-dev2:196:196 [1] NCCL INFO comm 0x5d77260 rank 1 nranks 2 cudaDev 1 busId 3f000 - Init COMPLETE
```

**Pull request merged**
